### ISSUE TITLE
Create transition roadmap to ReactOnRails

### ISSUE THREAD

**Issue by ahangarha** [shakacode/react-rails-example-app#4]
To show the transition, we can just create a PR that transitions to ReactOnRails and will never be merged.

**Comment by ahangarha** [comment]
The migration to ReactOnRails can be seen in [react-rails-to-react-on-rails](https://github.com/shakacode/react-rails-example-app/tree/react-rails-to-react-on-rails) branch

## Todo:
- [x] New branch demonstrating the migration
- [ ] Update docs in the migration branch
- [ ] Update ready on master, mentioning the migration branch
